---
logstash_version: '7.10.2'

logstash_package: logstash

logstash_listen_port_beats: 5044

logstash_elasticsearch_hosts:
  - http://localhost:9200

logstash_local_syslog_path: /var/log/syslog
logstash_monitor_local_syslog: false

logstash_dir: /usr/share/logstash

logstash_ssl_dir: /etc/pki/logstash
logstash_ssl_certificate_file: ""
logstash_ssl_key_file: ""

logstash_enabled_on_boot: true

logstash_install_plugins:
  - logstash-input-s3
  - logstash-filter-mutate
  - logstash-filter-geoip
  - logstash-filter-grok
  - logstash-filter-http
  - logstash-output-amazon_es
  - logstash-output-elasticsearch
