apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    {{- include "fluentd_cet.labels" . | nindent 4 }}
  name: fluentd_cet-prometheus-conf
data:
  prometheus.conf: |-
    <source>
      @type prometheus
      @log_level debug
      bind 0.0.0.0
      port 24231
      metrics_path /metrics
    </source>
    
    <source>
      @type prometheus_monitor
    </source>
    
    <source>
      @type prometheus_output_monitor
    </source>
