---
# vars file for docker_engine
ansible_user: ubuntu

# vars file for docker image
create_containers: 1
default_container_name: web_server
default_container_image: nginx:latest
default_container_command: sleep 1d
default_container_exposed_port: 8080