---
- name: Register Elasticsearch service
  when: hostvars[inventory_hostname].tags.consul_server == 'elasticsearch_1'
  copy:
    src: elasticsearch_service.json
    dest: /etc/consul.d/elasticsearch_service.json

- name: Register Prometheus service
  when: service == "prometheus" and instance_type == "server"
  copy:
    src: prometheus_service.json
    dest: /etc/consul.d/prometheus_service.json