---
# defaults file for install-prometheus
prometheus_version: 2.34.0
prometheus_binary_local_dir: ''
prometheus_skip_install: false

prometheus_config_dir: /etc/prometheus
prometheus_db_dir: /data/prometheus
prometheus_read_only_dirs: []

prometheus_storage_retention: "30d"
prometheus_storage_retention_size: "0"

prometheus_web_listen_address: "0.0.0.0:9090"
prometheus_web_external_url: ''

prometheus_config_flags_extra: {}
# prometheus_config_flags_extra:
#   storage.tsdb.retention: 15d
#   alertmanager.timeout: 10s




