{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "fluentd_cet.fullname" . }}
  labels:
    {{- include "fluentd_cet.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - namespaces
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - policy
    resourceNames:
      - {{ include "fluentd_cet.fullname" . }}
    resources:
      - podsecuritypolicies
    verbs:
      - use
{{- end -}}
