
apiVersion: v1
kind: Service
metadata:
  name: {{ include "fluentd_cet.fullname" . }}
  labels:
    {{- include "fluentd_cet.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: 24231
    targetPort: metrics
    protocol: TCP
    name: metrics
  {{- if .Values.service.ports }}
  {{- range $port := .Values.service.ports }}
  - name: {{ $port.name }}
    port: {{ $port.containerPort }}
    targetPort: {{ $port.containerPort }}
    protocol: {{ $port.protocol }}
  {{- end }}
  {{- end }}
  selector:
    {{- include "fluentd_cet.selectorLabels" . | nindent 4 }}
