filebeat.inputs:
  - type: log
    enabled: false
    paths:
      - /var/log/auth.log
filebeat.modules:
  - module: system
    syslog:
      enabled: true
    auth:
      enabled: true
filebeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false
setup.dashboards.enabled: true
setup.template.name: "filebeat"
setup.template.pattern: "filebeat-*"
setup.template.settings:
  index.number_of_shards: 1
processors:
  - add_host_metadata:
      when.not.contains.tags: forwarded
  - add_cloud_metadata: ~
output.elasticsearch:
  hosts: ["elasticsearch-1.kandula.int:9200"]
  index: "filebeat-%{+yyyy.MM.dd}"

setup.kibana:
  host: "elasticsearch-1.kandula.int:5601"
  protocol: "http"
  ssl.enabled: false