---
# my web server configurations
- name: apply consul server installation on my consul servers
  hosts: tag_consul_server_true
  become: yes
  become_user: root
  become_method: sudo
  vars:
    ansible_python_interpreter: /usr/bin/python3

  roles:
    - consul