- name: apply registrator installation on my servers
  hosts: tag_docker_engine_true
  remote_user: ubuntu
  become: yes
  become_user: root
  become_method: sudo
  vars:
    ansible_python_interpreter: /usr/bin/python3
  roles:
    - consul_registrator