---
# my web server configurations
- name: apply docker eng installation on my jenkins-master & jenkins-slave
  hosts: tag_Name_jenkins_slave
  become: yes
  vars:
    default_container_name: consul_registrator
    default_container_image: gliderlabs/registrator:latest
    default_container_command: --net=host --volume=/var/run/docker.sock:/tmp/docker.sock consul://localhost:8500

  tasks:
    - name: Create default containers
      docker_container:
        name: "{{ default_container_name }}{{ item }}"
        image: "{{ default_container_image }}"
        pull: true
        command: "{{ default_container_command }}"
        state: started