- name: apply logstash installation on jenkins-slave server
  hosts: tag_Name_jenkins_slave
  remote_user: ubuntu
  become: yes
  become_user: root
  become_method: sudo
  vars:
    ansible_python_interpreter: /usr/bin/python3
  roles:
    - logstash