- name: apply node_exporter installation on my servers
  hosts: tag_node_exporter_true
  remote_user: ubuntu
  become: yes
  become_user: root
  become_method: sudo
  vars:
    ansible_python_interpreter: /usr/bin/python3
  roles:
    - node_exporter